version: '2'
services:
  api:
    image: atopy/api-drive
    command: npm run start
    ports:
      - "3000:3000"
  front:
    image: thilaire/alps-drive-frontend
    ports:
      - "8080:80"
    depends_on:
      - api