version: '2'
services:
  api:
    build: .
    command: npm run dev
    volumes:
      - .:/usr/app/
      - /usr/app/node_modules
    ports:
      - "3000:3000"
  front:
    image: thilaire/alps-drive-frontend
    ports:
      - "8080:80"
    depends_on:
      - api